### ISSUE TITLE
Training Code Release ?

### ISSUE THREAD

**Issue by Kunaldargan** [suhwan-cho/BMVOS#2]
Hi,
Thank you for providing exceptionally well-written code for your paper. 
Kindly let me know where is the training code if present in the repository?
If not released yet, do you have a plan to release it?

Regards

**Comment by suhwan-cho** [comment]
Unfortunately, we don't have any plan to release the code at this point.

**Comment by suhwan-cho** [comment]
Hi,
Sorry for late reply.
Training code is now updated!

**Comment by suhwan-cho** [comment]
Hi,
Sorry for late reply.
Training code is now available!
